name: Python tests
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      use_venv: # usage
        description: 'Whether or not to use python virtual environment'
        default:     'true'
        required:    true
      name:
        description: A cli input to be tested against the generated programme
        default:     'max mustermann'
        required:    true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Install system requirements via apt-get
      run: |-
        apt-get -y update && \
        apt-get -y upgrade && \
        apt-get install -y dos2unix && \
        apt-get install -y apt-utils && \
        apt-get install -y zip unzip xz-utils && \
        apt-get clean
    - name: Grant execution rights
      run: chmod +x scripts/*.sh
    - name: Run setup
      run: ./scripts/build.sh --venv ${{ github.event.inputs.use_venv }} --mode setup
    - name: Check if open source code works
      run: python3 src/main.py name="${{ github.event.inputs.name }}"
    - name: Check if artefact exists before creation
      run: |-
        ls;
        ls dist/*;
        [ -f dist/sandboxapp ] && echo "artefact exists" || echo "artefact does not exists";
    - name: Create artefact
      run: ./scripts/build.sh --mode dist
    - name: Check if artefact created
      run: |-
        ls;
        ls dist/*;
        [ -f dist/sandboxapp ] && echo "artefact exists" || echo "artefact does not exists";
    - name: Check if programme works
      run: dist/sandboxapp name="${{ github.event.inputs.name }}"
    - name: End of test
      run: echo "End"
